// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2FXVFnc5_tMKF_6UoHMPUYQixDeEBN7k',
    appId: '1:476386945179:web:66cb674ac884ecd131fe3e',
    messagingSenderId: '476386945179',
    projectId: 'bazooka-34346',
    authDomain: 'bazooka-34346.firebaseapp.com',
    storageBucket: 'bazooka-34346.firebasestorage.app',
    measurementId: 'G-CE7CJLQNQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyG8GzNVLoKy_AP4Hh04F8VXZt1MWckRY',
    appId: '1:476386945179:android:87e335629fa64ea731fe3e',
    messagingSenderId: '476386945179',
    projectId: 'bazooka-34346',
    storageBucket: 'bazooka-34346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1oFECKgFcRu_rV8E_SnMwttBjllaD35s',
    appId: '1:476386945179:ios:c24444b8361ef2bf31fe3e',
    messagingSenderId: '476386945179',
    projectId: 'bazooka-34346',
    storageBucket: 'bazooka-34346.firebasestorage.app',
    iosBundleId: 'com.example.secondTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1oFECKgFcRu_rV8E_SnMwttBjllaD35s',
    appId: '1:476386945179:ios:c24444b8361ef2bf31fe3e',
    messagingSenderId: '476386945179',
    projectId: 'bazooka-34346',
    storageBucket: 'bazooka-34346.firebasestorage.app',
    iosBundleId: 'com.example.secondTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2FXVFnc5_tMKF_6UoHMPUYQixDeEBN7k',
    appId: '1:476386945179:web:91732dfe1c19351f31fe3e',
    messagingSenderId: '476386945179',
    projectId: 'bazooka-34346',
    authDomain: 'bazooka-34346.firebaseapp.com',
    storageBucket: 'bazooka-34346.firebasestorage.app',
    measurementId: 'G-1QZFJT87H4',
  );
}
